modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/TerraformersMC/Biolith/issues"
license = "LGPL-3.0"

[[mods]]
modId = "biolith"
version = "${version}"
displayName = "Biolith"
displayURL="https://modrinth.com/mod/biolith"
authors = "TerraformersMC, gniftygnome"
description = '''
Terraformers' world generation utilities
'''
logoFile = "assets/biolith/logo.png"

[[mixins]]
config = "biolith.mixins.json"
[[mixins]]
config = "biolith.neoforge.mixins.json"

[[dependencies.biolith]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biolith]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.21.4)"
ordering = "NONE"
side = "BOTH"
